### ISSUE TITLE
Suggestion: possible to add BrowserSync?

### ISSUE THREAD

**Issue by bekapod** [inviqa/deck-task-registry#23]
I'm not 100% sure how this would work with our current workflow (every user on a different remote IP) so if this is impossible feel free to disregard.

**Comment by bekapod** [comment]
Have KINDA got an idea of how it could work: https://github.com/bekapod/deck-task-registry/commit/98d721fde97672a140693f994fb7bb71824474e0 but I'm not 100% sure how I can test this as part of my theme to make sure it works (ie. pull in this branch instead of deck-task-registry:master)

**Comment by Chapabu** [comment]
If you clean out the node_modules directory in the project that's using deck-task-registry, then in your fork run `npm link`, then back in the project run `npm-link deck-task-registry`, then it should symlink to your fork.

Although, I'm not sure how this will work in practice, as we should be running the gulp tasks on the remote, but you'd have to run browserSync locally to get any real benefit. Doesn't that mean you'd have the tools running in two places?

Also, I'm interested in the use-case for this. I wonder if we can take the useful bits of browserSync and make something that fits our workflow with https://github.com/BrianDGLS/fs-broadcaster?

**Comment by Chapabu** [comment]
If it's just for the auto reloading, then I reckon we can use the above fs-broadcaster and throw some JS in the main Deck theme to auto refresh the CSS/JS when it changes on the remote? Is that the end goal?
